name: Private

on:
  workflow_dispatch:

jobs:
  change-visibility:
    runs-on: ubuntu-slim
    steps:
      - name: Change Visibility
        uses: JustinBird/github-visibility-action@main
        with:
          visibility: private
          token: ${{ secrets.ADMINISTRATION_TOKEN }}
